openapi: 3.0.3
info:
  title: User Information Service
  description: FABRIC User Information Service
  termsOfService: None
  contact:
    name: Ilya Baldin
    url: https://www.fabric-testbed.net
    email: ibaldin@renci.org
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.1.0
servers:
- url: http://127.0.0.1:5000/
  description: local development
- url: https://virtserver.swaggerhub.com/fabric-testbed/user-information-service/1.1.0
  description: SwaggerHub API Auto Mocking
tags:
- name: people
  description: People known to FABRIC UIS
  externalDocs:
    description: Private design docs
    url: https://docs.google.com/document/d/1rqM4TNarqyO8JRg6nycX1Tyu7ctYzjzcTkjDKLs6G64/edit#
- name: preferences
  description: Portal preference information
  externalDocs:
    description: Private design docs
    url: https://docs.google.com/document/d/1rqM4TNarqyO8JRg6nycX1Tyu7ctYzjzcTkjDKLs6G64/edit#
- name: keys
  description: SSH key information
  externalDocs:
    description: Private design docs
    url: https://docs.google.com/document/d/1rqM4TNarqyO8JRg6nycX1Tyu7ctYzjzcTkjDKLs6G64/edit#
- name: publications
  description: Publication information
  externalDocs:
    description: Private design docs
    url: https://docs.google.com/document/d/1rqM4TNarqyO8JRg6nycX1Tyu7ctYzjzcTkjDKLs6G64/edit#
paths:
  /version:
    get:
      tags:
      - default
      summary: version (open)
      description: Version
      operationId: version_get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /uuid/oidc_claim_sub:
    get:
      tags:
      - people
      summary: get person UUID based on their OIDC claim sub (open to any valid user)
      description: person UUID based on their OIDC claim sub
      operationId: uuid_oidc_claim_sub_get
      parameters:
      - name: oidc_claim_sub
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: People not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.people_controller
  /people:
    get:
      tags:
      - people
      summary: list of people (open to any valid user)
      description: List of people
      operationId: people_get
      parameters:
      - name: person_name
        in: query
        description: Search People by Name (ILIKE)
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/People_short'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: People not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.people_controller
  /people/whoami:
    get:
      tags:
      - people
      summary: Details about self from OIDC Claim sub provided in ID token; Creates
        new entry; (open only to self)
      description: Details about self based on key OIDC Claim sub contained in ID
        token; Creates new entry
      operationId: people_whoami_get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/People_long'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: People not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.people_controller
  /people/{uuid}:
    get:
      tags:
      - people
      summary: person details by UUID (open only to self)
      description: Person details by UUID
      operationId: people_uuid_get
      parameters:
      - name: uuid
        in: path
        description: People identifier as UUID
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/People_long'
        "400":
          description: Bad request. People ID must be in uuid-4 format
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: A Person with the specified ID was not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.people_controller
  /preferences/{preftype}/{uuid}:
    get:
      tags:
      - preferences
      summary: "get user preferences of specific type (settings, permissions or interests;\
        \ open only to self)"
      description: "User preferences (returns sane defaults if user valid, but preferences\
        \ not available)"
      operationId: preferences_preftype_uuid_get
      parameters:
      - name: preftype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PreferenceType'
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
        "204":
          description: Preference not found
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Person/UUID not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.preferences_controller
    put:
      tags:
      - preferences
      summary: update user preferences by type (open only to self)
      description: Update specific type of user preferences
      operationId: preferences_preftype_uuid_put
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: preftype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PreferenceType'
      - name: preferences
        in: query
        required: true
        style: deepObject
        explode: false
        schema:
          type: object
          additionalProperties: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: A User with the specified ID was not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.preferences_controller
  /preferences/{uuid}:
    get:
      tags:
      - preferences
      summary: get all user preferences as an object (open only to self)
      description: Get all preferences for a user
      operationId: preferences_uuid_get
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preferences'
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Person/UUID not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.preferences_controller
  /authorids/{uuid}:
    get:
      tags:
      - publications
      summary: "get user's author IDs (Scopus, Orcid etc.; open only to self)"
      operationId: authorids_uuid_get
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AuthorId'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Person matching UUID not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.publications_controller
  /authorids/{idtype}/{uuid}:
    get:
      tags:
      - publications
      summary: get users specific author ID (open only to self)
      operationId: authorids_idtype_uuid_get
      parameters:
      - name: idtype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/AuthorIdType'
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "204":
          description: This type author ID not found
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Person with UUID not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.publications_controller
    put:
      tags:
      - publications
      summary: update user's specific author ID (open only to self)
      operationId: authorids_idtype_uuid_put
      parameters:
      - name: idtype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/AuthorIdType'
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: idval
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: People not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.publications_controller
  /sshkey/{keytype}:
    put:
      tags:
      - sshkeys
      summary: Generate a new SSH key of specified type. Return both public and private
        portions. (open only to self)
      operationId: sshkey_keytype_put
      parameters:
      - name: keytype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/SshKeyType'
      - name: comment
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: description
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SshKeyPair'
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Keys not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
    post:
      tags:
      - sshkeys
      summary: Add a user-provided ssh public key of specified type. (open only to
        self)
      operationId: sshkey_keytype_post
      parameters:
      - name: keytype
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/SshKeyType'
      - name: public_openssh
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: description
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Keys not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
  /sshkey/{uuid}/{keyid}:
    get:
      tags:
      - sshkeys
      summary: Get a specific key of a given user (open to any valid user)
      operationId: sshkey_uuid_keyid_get
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: keyid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SshKeyLong'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Keys not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
  /sshkey/{keyid}:
    get:
      tags:
      - sshkeys
      summary: "get metadata, including expiration date for this key based on key\
        \ UUID (open only to self)"
      operationId: sshkey_keyid_get
      parameters:
      - name: keyid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SshKeyLong'
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Key not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
    delete:
      tags:
      - sshkeys
      summary: Delete a specified key based on key UUID (open only to self)
      operationId: sshkey_keyid_delete
      parameters:
      - name: keyid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: People not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
  /sshkeys:
    get:
      tags:
      - sshkeys
      summary: Get a list of all active/non-expired keys of this user (open to self)
      operationId: sshkeys_get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SshKeyLong'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Keys not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
  /bastionkeys:
    get:
      tags:
      - sshkeys
      summary: "Get a list of bastion keys that were created, deactivated or expired\
        \ since specified date in UTC (open to Bastion hosts)"
      operationId: bastionkeys_get
      parameters:
      - name: secret
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: since_date
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SshKeyBastion'
                x-content-type: application/json
        "400":
          description: Bad request
        "401":
          description: Authorization information is missing or invalid
        "404":
          description: Keys not found
        "5XX":
          description: Unexpected error
      x-openapi-router-controller: swagger_server.controllers.sshkeys_controller
components:
  schemas:
    Version:
      properties:
        version:
          type: string
        gitsha1:
          type: string
      example:
        gitsha1: gitsha1
        version: version
    People_short:
      properties:
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
        eppn:
          type: string
        oidc_claim_sub:
          type: string
      example:
        eppn: eppn
        name: name
        uuid: uuid
        oidc_claim_sub: oidc_claim_sub
        email: email
    People_long:
      properties:
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
        eppn:
          type: string
        oidc_claim_sub:
          type: string
        bastion_login:
          type: string
        prefs:
          $ref: '#/components/schemas/Preferences'
      example:
        eppn: eppn
        name: name
        uuid: uuid
        oidc_claim_sub: oidc_claim_sub
        bastion_login: bastion_login
        email: email
        prefs:
          settings: {}
          permissions: {}
          interests: {}
    Preferences:
      properties:
        settings:
          type: object
        permissions:
          type: object
        interests:
          type: object
      example:
        settings: {}
        permissions: {}
        interests: {}
    SshKeyPair:
      properties:
        private_openssh:
          type: string
        public_openssh:
          type: string
      description: SSH Key Pair
      example:
        private_openssh: private_openssh
        public_openssh: public_openssh
    SshKeyShort:
      properties:
        key_uuid:
          type: string
        name:
          type: string
        comment:
          type: string
        description:
          type: string
        fingerprint:
          type: string
        public_key:
          type: string
      description: Public SSH key short version
    SshKeyLong:
      properties:
        key_uuid:
          type: string
        public_key:
          type: string
        name:
          type: string
        comment:
          type: string
        description:
          type: string
        fingerprint:
          type: string
        created_on:
          type: string
        expires_on:
          type: string
        deactivated_on:
          type: string
        deactivation_reason:
          type: string
      description: Public SSH key long version
      example:
        public_key: public_key
        deactivation_reason: deactivation_reason
        key_uuid: key_uuid
        created_on: created_on
        expires_on: expires_on
        name: name
        fingerprint: fingerprint
        description: description
        comment: comment
        deactivated_on: deactivated_on
    SshKeyBastion:
      properties:
        public_openssh:
          type: string
        login:
          type: string
        status:
          $ref: '#/components/schemas/SshKeyStatus'
      description: SSH key info for bastion host
      example:
        public_openssh: public_openssh
        login: login
        status: deactivated
    SshKeyType:
      type: string
      description: Type of SSH key
      enum:
      - sliver
      - bastion
    SshKeyStatus:
      type: string
      description: Status of SSH key
      enum:
      - deactivated
      - expired
      - active
    AuthorIdType:
      type: string
      description: Different possible types of author IDs
      enum:
      - orcid
      - publons
      - scopus
    AuthorId:
      properties:
        idtype:
          $ref: '#/components/schemas/AuthorIdType'
        idvalue:
          type: string
      description: Tuple describing an author ID (type and value)
      example:
        idtype: orcid
        idvalue: idvalue
    PreferenceType:
      type: string
      description: Portal preferences come in a small number of flavors
      enum:
      - settings
      - permissions
      - interests

